import java.util.Random;

public class WordleOrd {


    String[] words = new String[]{
            "ABBED", "ABORT", "ACCES", "ADEPT", "ADLYD", "ADLØD", "ADRÆT", "ADVIS", "AEROB", "AFART", "AFASI", "AFBAR",
            "AFBUD", "AFDØD", "AFGAV", "AFGIK", "AFGIV", "AFGUD", "AFGØR", "AFGÅR", "AFGÅS", "AFHOP", "AFILM", "AFISE",
            "AFKOG", "AFKOM", "AFLAD", "AFLOD", "AFLYD", "AFLÆG", "AFLØB", "AFPIL", "AFREV", "AFRIV", "AFSAT", "AFSER",
            "AFSES", "AFSET", "AFSIG", "AFSKY", "AFSLÅ", "AFSTÅ", "AFSÆT", "AFSÅS", "AFTAG", "AFTEN", "AFTER", "AFTES",
            "AFTOG", "AFTÆL", "AFVEG", "AFVEJ", "AFVIG", "AGAPE", "AGAVE", "AGENS", "AGENT", "AGERE", "AGERN", "AGONI",
            "AGORA", "AGRAR", "AGTEN", "AGTER", "AGURK", "AHOLD", "AHORN", "AJOUR", "AKRYL", "AKSEL", "AKSLE", "AKTIE",
            "AKTIV", "AKTOR", "AKTØR", "ALARM", "ALBUE", "ALBUM", "ALDER", "ALDRE", "ALENE", "ALERT", "ALGOD", "ALHED",
            "ALHUS", "ALIAS", "ALIBI", "ALKEN", "ALKYD", "ALLER", "ALLES", "ALLÉS", "ALMEN", "ALMUE", "ALPIN", "ALRUM",
            "ALTAN", "ALTER", "ALTID", "ALTRE", "ALTSÅ", "ALVOR", "AMBRA", "AMORF", "AMPEL", "AMPUL", "AMØBE", "ANDEL",
            "ANDEN", "ANDET", "ANDRE", "ANGAV", "ANGER", "ANGIK", "ANGIV", "ANGLE", "ANGRE", "ANGST", "ANGÅR", "ANGÅS",
            "ANION", "ANJON", "ANKEL", "ANKER", "ANKOM", "ANKRE", "ANLÆG", "ANLØB", "ANNAL", "ANNUA", "ANODE", "ANOMI",
            "ANRÅB", "ANSAT", "ANSER", "ANSES", "ANSET", "ANSLÅ", "ANSTÅ", "ANSÆT", "ANSÅS", "ANTAG", "ANTAL", "ANTIK",
            "ANTOG", "ANÆMI", "AORTA", "APATI", "APPEL", "APRIL", "APSIS", "AREAL", "ARENA", "ARGON", "ARIER", "ARISK",
            "ARKIV", "ARMES", "ARMÉS", "ARMOD", "AROMA", "ARRAK", "ARRET", "ARRIG", "ARSEN", "ARTIG", "ARVÆV", "ASENS",
            "ASIAT", "ASIDE", "ASIET", "ASKET", "ASNER", "ASNET", "ASPEN", "ASPES", "ASTMA", "ASTRO", "ATLAS", "ATLET",
            "ATTAK", "ATTEN", "ATTER", "ATTRÅ", "AUDIT", "AUGUR", "AUTOR", "AVERS", "AVIND", "AVLER",
            "BACKS", "BACON", "BADER", "BADES", "BADGE", "BADUT", "BAGEL", "BAGER", "BAGOM", "BAGPÅ", "BAGTÅ", "BAGUD",
            "BAJER", "BAKKE", "BAKSE", "BALAN", "BALDE", "BALJE", "BALLE", "BAMLE", "BAMSE", "BANAL", "BANAN", "BANDE",
            "BANDT", "BANDY", "BANGE", "BANJO", "BANKE", "BANKO", "BANTU", "BAPPE", "BARAK", "BARBE", "BARDE", "BARES",
            "BARET", "BARKE", "BARNE", "BARNS", "BAROK", "BARON", "BARRE", "BARSK", "BARYL", "BASAL", "BASAR", "BASEN",
            "BASER", "BASIS", "BASKE", "BASSE", "BASTA", "BASTE", "BASUN", "BATAT", "BATCH", "BATIK", "BATTE", "BAVLE",
            "BEBOP", "BEDER", "BEDES", "BEDRE", "BEDST", "BEDTE", "BEDTS", "BEDØM", "BEFAR", "BEFOR", "BEFRI", "BEGAV",
            "BEGET", "BEGGE", "BEGIK", "BEGIV", "BEGLO", "BEGÆR", "BEGÅR", "BEGÅS", "BEHAG", "BEHOV", "BEIGE", "BEJAE",
            "BEJLE", "BEKOM", "BELIG", "BELÆG", "BELØB", "BELØJ", "BELÅS", "BENET", "BENLI", "BERET", "BERYL", "BESAD",
            "BESAT", "BESER", "BESES", "BESET", "BESID", "BESLÅ", "BESOV", "BESTÅ", "BESYV", "BESÆT", "BESØG", "BESÅS",
            "BETEL", "BETES", "BETLE", "BETOG", "BETON", "BETRO", "BETØD", "BEVIS", "BEÆRE", "BHOLD", "BHSÆT", "BIAVL",
            "BIBEL", "BIDER", "BIDES", "BIDET", "BIDSK", "BIDTE", "BIDTS", "BIFAG", "BIFIL", "BIGOT", "BIJOB", "BIKER",
            "BIKIR", "BIKSE", "BILAG", "BILDE", "BILED", "BILKØ", "BILLE", "BILOS", "BILYD", "BIMLE", "BINDE", "BINGO",
            "BINÆR", "BIORD", "BIPPE", "BISAG", "BISAM", "BISAT", "BISOL", "BISON", "BISSE", "BISTÅ", "BISÆT", "BITCH",
            "BITRE", "BITTE", "BIVEJ", "BIZAR", "BJERG", "BJESK", "BJÆRG", "BJØRN", "BLADE", "BLANK", "BLASE", "BLEEN",
            "BLEER", "BLEGE", "BLEGN", "BLIDE", "BLIDT", "BLIND", "BLINI", "BLINK", "BLIST", "BLITZ", "BLIVE", "BLOGS",
            "BLOND", "BLOTE", "BLUES", "BLUFF", "BLUND", "BLUSE", "BLÆRE", "BLÆSE", "BLÆST", "BLØDE", "BLÅNE", "BLÅTS",
            "BOBBE", "BOBLE", "BODEL", "BOGEN", "BOGIE", "BOJAR", "BOKSE", "BOLIG", "BOLLE", "BOLTE", "BOMBE", "BOMME",
            "BONDE", "BONUS", "BOOKE", "BOOME", "BOOTE", "BOPÆL", "BORDE", "BORGE", "BORST", "BORTE", "BOSAT", "BOSSE",
            "BOSÆT", "BOULE", "BOVIN", "BOVNE", "BOWLE", "BOXER", "BRAGE", "BRAGT", "BRAND", "BRASE", "BRASK", "BRAST",
            "BRAVO", "BREAK", "BREDE", "BRIKS", "BRING", "BRINK", "BRINT", "BRISE", "BRIST", "BRITE", "BRORS", "BRUDT",
            "BRUGE", "BRUGS", "BRUGT", "BRUNE", "BRUSE", "BRUSK", "BRYDE", "BRYNE", "BRYSK", "BRYST", "BRÆGE", "BRÆTS",
            "BRØDE", "BRØLE", "BRØND", "BRØST", "BSIDE", "BSKÅL", "BUDTE", "BUDTS", "BUGGY", "BUGNE", "BUGTE", "BUKET",
            "BUKKE", "BUKLE", "BUKSE", "BULET", "BULKE", "BULLE", "BULNE", "BUMLE", "BUMPE", "BUMSE", "BUNDE", "BUNDT",
            "BUNKE", "BURDE", "BURKA", "BURRE", "BURÆG", "BUSSE", "BUSTE", "BUTAN", "BUTIK", "BUZZE", "BVADR", "BYBIL",
            "BYBUD", "BYBUS", "BYDEL", "BYDER", "BYDES", "BYGAS", "BYGGE", "BYHUS", "BYLIV", "BYLTE", "BYMUR", "BYNKE",
            "BYNÆR", "BYRDE", "BYRET", "BYROD", "BYRUM", "BYRÅD", "BYSSE", "BYSTE", "BYTTE", "BYTUR", "BYTYR", "BZHUS",
            "BÆGER", "BÆGRE", "BÆLGE", "BÆLLE", "BÆLTE", "BÆNKE", "BÆRER", "BÆRES", "BÆRME", "BÆVEN", "BÆVER", "BÆVRE",
            "BØDES", "BØFFE", "BØGER", "BØJLE", "BØLGE", "BØLLE", "BØNNE", "BØRNE", "BØRNS", "BØSSE", "BØTTE", "BØVET",
            "BØVLE", "BØVSE", "BÅNDE", "BÅREN", "BÅRET", "BÅRNE", "BÅTTE",
            "CACHE", "CAFES", "CAFÉS", "CASEN", "CASES", "CASTE", "CEDER", "CELLE", "CELLO", "CENTI", "CERUT", "CHARM",
            "CHATS", "CHECK", "CHILI", "CHIPS", "CHOLD", "CHROM", "CIDER", "CIFRE", "CIGAR", "CIRKA", "CIRRI", "CITAR",
            "CITAT", "CITER", "CITRE", "CIVIL", "CLEAN", "CLICK", "CLIPS", "COACH", "COATE", "CONGA", "COOLS", "CORNY",
            "COUPE", "COUPÉ", "COVER", "CPUEN", "CPUER", "CRAWL", "CRAZY", "CREDO", "CREME", "CREPE", "CROSS", "CSKÅL",
            "CURIE", "CUTTE", "CYKEL", "CYKLE", "CYSTE", "CÆSAR", "CÆSUR",
            "DADEL", "DADLE", "DAFFE", "DAFNE", "DAGES", "DALBO", "DALER", "DALRE", "DAMET", "DAMPE", "DANBO", "DANDY",
            "DANER", "DANNE", "DANSE", "DANSK", "DASKE", "DATEN", "DATES", "DATID", "DATIV", "DATJA", "DAVID", "DAVRE",
            "DEBAT", "DEBET", "DEBIL", "DEBUT", "DECCA", "DEJSE", "DEKAN", "DEKOR", "DELER", "DELLE", "DELTA", "DELTE",
            "DELTS", "DENAR", "DENIM", "DENNE", "DENTE", "DEPOT", "DERAF", "DERBY", "DERES", "DEROM", "DEROP", "DERPÅ",
            "DERUD", "DESTO", "DETTE", "DEVON", "DIBLE", "DIGEL", "DIGER", "DIGRE", "DIGTE", "DIKKE", "DILDO", "DILLE",
            "DINAR", "DINER", "DINES", "DINGO", "DIODE", "DIPOL", "DIRKE", "DIRRE", "DISCO", "DISET", "DISKE", "DISSE",
            "DITTO", "DIVAN", "DJÆRV", "DOBLE", "DOGGE", "DOGME", "DOKKE", "DOLCE", "DOLKE", "DOLME", "DONNA", "DONOR",
            "DORER", "DORSK", "DOSEN", "DOSER", "DOSIS", "DOUCE", "DOVEN", "DOVNE", "DOYEN", "DRAGE", "DRAGÉ", "DRAGS",
            "DRAGT", "DRAMA", "DRAPS", "DREJE", "DREJL", "DRENG", "DRESS", "DRIFT", "DRINK", "DRIVE", "DROGE", "DRONE",
            "DROPS", "DRUDE", "DRUGS", "DRYAS", "DRÆBE", "DRÆNE", "DRÆVE", "DRØJE", "DRØMT", "DRØNE", "DRÅBE", "DUBBE",
            "DUBLE", "DUBLÉ", "DUFTE", "DUGGE", "DUKAT", "DUKKE", "DULGT", "DULLE", "DULME", "DUMME", "DUMMY", "DUMPE",
            "DUNET",
            "DUNKE",
            "DUNST",
            "DUPPE",
            "DURRA",
            "DURRE",
            "DUSIN",
            "DUSSE",
            "DUSØR",
            "DUTTE",
            "DUVEN",
            "DVALE",
            "DVASK",
            "DVÆLE",
            "DVÆRG",
            "DYBDE",
            "DYBEL",
            "DYBSØ",
            "DYDIG",
            "DYKKE",
            "DYNGE",
            "DYPPE",
            "DYRKE",
            "DYSSE",
            "DYSTE",
            "DYTTE",
            "DYVEL",
            "DÆGGE",
            "DÆKKE",
            "DÆLEN",
            "DÆLME",
            "DÆMME",
            "DÆMON",
            "DÆMPE",
            "DÆMRE",
            "DÆNGE",
            "DÆVEL",
            "DÆVLE",
            "DØBER",
            "DØDES",
            "DØDIS",
            "DØETS",
            "DØLGE",
            "DØLLE",
            "DØMME",
            "DØMTE",
            "DØMTS",
            "DØNNE",
            "DØSIG",
            "DØTRE",
            "DÅDYR",
            "DÅLAM",
            "EBOLA",
            "EBREV",
            "EDBEN",
            "EDDER",
            "EDERS",
            "EDIKT",
            "EFFEN",
            "EFGER",
            "EFTER",
            "EGENS",
            "EGENT",
            "EGERN",
            "EGETS",
            "EGNES",
            "EGNET",
            "EKKOE",
            "EKSEM",
            "EKSER",
            "EKSES",
            "EKSET",
            "EKSIL",
            "ELBAS",
            "ELBIL",
            "ELEGI",
            "ELGKO",
            "ELITE",
            "ELLER",
            "ELSKE",
            "ELTOG",
            "ELVER",
            "EMAIL",
            "EMMER",
            "EMSIG",
            "ENDDA",
            "ENDNU",
            "ENDOG",
            "ENGEL",
            "ENGLE",
            "ENHED",
            "ENIGT",
            "ENKEL",
            "ENKLE",
            "ENLIG",
            "ENORM",
            "ENRUM",
            "ENSES",
            "ENSOM",
            "ENTAL",
            "ENTEN",
            "ENTRE",
            "ENTRÉ",
            "ENZYM",
            "ENØRE",
            "EPISK",
            "EPOKE",
            "EPOST",
            "EPOXY",
            "ERIKA",
            "ERLÆG",
            "ERMOL",
            "ESMOL",
            "ESPEN",
            "ESPES",
            "ESROM",
            "ESSAY",
            "ESSIG",
            "ESTER",
            "ETAGE",
            "ETAPE",
            "ETBÆR",
            "ETISK",
            "ETMÅL",
            "ETTAL",
            "ETTER",
            "ETUDE",
            "ETÅRS",
            "EUNUK",
            "EVENT",
            "EVERT",
            "EXCES",
            "EXEDE",
            "EXETS",
            "FABEL",
            "FABLE",
            "FACET",
            "FACIL",
            "FACIT",
            "FACON",
            "FACTO",
            "FACTS",
            "FADER",
            "FADØL",
            "FAGER",
            "FAGOT",
            "FAGRE",
            "FAIRS",
            "FAKIR",
            "FAKTA",
            "FALDE",
            "FALDT",
            "FALLE",
            "FALME",
            "FALSK",
            "FAMLE",
            "FAMØS",
            "FANCY",
            "FANDT",
            "FANGE",
            "FANME",
            "FANSS",
            "FARAD",
            "FARAO",
            "FARCE",
            "FAREN",
            "FARER",
            "FARES",
            "FARET",
            "FARIN",
            "FARNE",
            "FARSI",
            "FARTE",
            "FARVE",
            "FASAN",
            "FASTE",
            "FASTS",
            "FATAL",
            "FATAS",
            "FATTE",
            "FATUM",
            "FATWA",
            "FAUNA",
            "FAVNE",
            "FAVØR",
            "FEBER",
            "FEDME",
            "FEDTE",
            "FEENS",
            "FEERS",
            "FEHÅR",
            "FEJDE",
            "FEJLE",
            "FEJRE",
            "FEMTE",
            "FEMTI",
            "FEMÅR",
            "FENNE",
            "FENOL",
            "FENYL",
            "FERIE",
            "FERLE",
            "FERRO",
            "FERSK",
            "FESES",
            "FESET",
            "FESTE",
            "FIBER",
            "FICUS",
            "FIDEL",
            "FIDUS",
            "FIFLE",
            "FIGEN",
            "FIGHT",
            "FIGUR",
            "FIKSE",
            "FILET",
            "FILME",
            "FILTE",
            "FILUR",
            "FIMRE",
            "FIMSE",
            "FINAL",
            "FINDE",
            "FINER",
            "FINÉR",
            "FINIS",
            "FINIT",
            "FINKE",
            "FINNE",
            "FINSK",
            "FINTE",
            "FIOLE",
            "FIRER",
            "FIRMA",
            "FIRME",
            "FISER",
            "FISES",
            "FISET",
            "FISKE",
            "FISSE",
            "FISTE",
            "FISTS",
            "FJANT",
            "FJASE",
            "FJELD",
            "FJERN",
            "FJERS",
            "FJERT",
            "FJOGE",
            "FJOLS",
            "FJONG",
            "FJORD",
            "FJÆLE",
            "FJÆRT",
            "FLADE",
            "FLAGE",
            "FLAIR",
            "FLANE",
            "FLASH",
            "FLERE",
            "FLERS",
            "FLEST",
            "FLINK",
            "FLINT",
            "FLIRE",
            "FLIRT",
            "FLISE",
            "FLOKS",
            "FLORA",
            "FLOVE",
            "FLUAT",
            "FLUGT",
            "FLUID",
            "FLUKS",
            "FLUOR",
            "FLUTE",
            "FLYDE",
            "FLYDT",
            "FLYER",
            "FLYVE",
            "FLÆBE",
            "FLÆNG",
            "FLÆSE",
            "FLÆSK",
            "FLØDE",
            "FLØJL",
            "FLØJT",
            "FLÅDE",
            "FNISE",
            "FNIST",
            "FNYSE",
            "FNYST",
            "FODEN",
            "FODER",
            "FODRE",
            "FOGED",
            "FOKUS",
            "FOLDE",
            "FOLDS",
            "FOLIE",
            "FOLIO",
            "FOLKE",
            "FONDS",
            "FONEM",
            "FONTO",
            "FORAN",
            "FORAS",
            "FORBI",
            "FORCE",
            "FORDI",
            "FOREL",
            "FOREN",
            "FORGÅ",
            "FORKE",
            "FORLÅ",
            "FORME",
            "FORMÅ",
            "FORNE",
            "FORNY",
            "FORPÅ",
            "FORRÅ",
            "FORSE",
            "FORST",
            "FORSÅ",
            "FORTE",
            "FORTI",
            "FORUD",
            "FORUM",
            "FORÆD",
            "FORÅD",
            "FORÅR",
            "FOSSE",
            "FOTON",
            "FOYER",
            "FRAGT",
            "FRAGÅ",
            "FRANC",
            "FRANK",
            "FRASE",
            "FREAK",
            "FREDE",
            "FREDS",
            "FRELS",
            "FREON",
            "FRIER",
            "FRISE",
            "FRISK",
            "FRIST",
            "FRONT",
            "FROST",
            "FRUGT",
            "FRYDE",
            "FRYGT",
            "FRYSE",
            "FRÆSE",
            "FRÅDE",
            "FRÅDS",
            "FRÅSE",
            "FUCKE",
            "FUGTE",
            "FULDE",
            "FULDT",
            "FULGT",
            "FUMLE",
            "FUNKE",
            "FUNKY",
            "FUPPE",
            "FURET",
            "FURIE",
            "FUSEL",
            "FUSER",
            "FUSKE",
            "FUTIL",
            "FUTON",
            "FUTTE",
            "FYGER",
            "FYGES",
            "FYGET",
            "FYLDE",
            "FYLDT",
            "FYLKE",
            "FYNBO",
            "FYNSK",
            "FYORD",
            "FYRIG",
            "FYRRE",
            "FYRÅB",
            "FYSIK",
            "FYTIN",
            "FÆCES",
            "FÆDRE",
            "FÆGTE",
            "FÆHÅR",
            "FÆISK",
            "FÆKAL",
            "FÆLDE",
            "FÆLLE",
            "FÆNGE",
            "FÆRGE",
            "FÆRRE",
            "FÆSTE",
            "FÆTRE",
            "FØDEØ",
            "FØGEN",
            "FØGET",
            "FØGNE",
            "FØJES",
            "FØJTE",
            "FØLER",
            "FØLGE",
            "FØLTE",
            "FØLTS",
            "FØRER",
            "FØRNE",
            "FØRST",
            "FÅEDE",
            "FÅETS",
            "FÅRET",
            "FÅTAL",
            "GABEN",
            "GAFFE",
            "GAFLE",
            "GAGSS",
            "GAKKE",
            "GALAN",
            "GALAR",
            "GALDE",
            "GALEJ",
            "GALEN",
            "GALGE",
            "GALLA",
            "GALLE",
            "GALON",
            "GALOP",
            "GALPE",
            "GAMBE",
            "GAMER",
            "GAMES",
            "GAMET",
            "GAMIN",
            "GAMLE",
            "GAMMA",
            "GANGE",
            "GARDE",
            "GARVE",
            "GASSE",
            "GAUGE",
            "GAVES",
            "GAVNE",
            "GEARE",
            "GEBET",
            "GEBIS",
            "GEBYR",
            "GEDDE",
            "GEEKS",
            "GEHØR",
            "GEJLE",
            "GEJSE",
            "GEJST",
            "GEKKO",
            "GELED",
            "GELES",
            "GELÉS",
            "GEMAK",
            "GEMAL",
            "GEMEN",
            "GEMME",
            "GEMSE",
            "GEMTE",
            "GEMTS",
            "GEMYT",
            "GENBO",
            "GENNE",
            "GENOM",
            "GENRE",
            "GENSE",
            "GENSÅ",
            "GENUA",
            "GENUS",
            "GERNE",
            "GEVIR",
            "GEVÆR",
            "GIBBE",
            "GIDER",
            "GIDES",
            "GIDET",
            "GIFTE",
            "GILDE",
            "GIMPE",
            "GIPSE",
            "GIRAF",
            "GISNE",
            "GISPE",
            "GITRE",
            "GIVEN",
            "GIVER",
            "GIVES",
            "GIVET",
            "GIVNE",
            "GJORD",
            "GJORT",
            "GLADE",
            "GLADS",
            "GLANE",
            "GLANS",
            "GLEMT",
            "GLIBE",
            "GLIDE",
            "GLIDS",
            "GLIMT",
            "GLOBE",
            "GLOSE",
            "GLÆDE",
            "GLØDE",
            "GLØGG",
            "GNAVE",
            "GNEJS",
            "GNIDE",
            "GNIER",
            "GNIST",
            "GNOME",
            "GODES",
            "GODTE",
            "GODTS",
            "GOKKE",
            "GONGE",
            "GOPLE",
            "GOTER",
            "GOTIK",
            "GOTTE",
            "GRADE",
            "GRAMS",
            "GRAND",
            "GRANT",
            "GRAVE",
            "GREEN",
            "GREJE",
            "GRENE",
            "GREVE",
            "GRIBE",
            "GRILL",
            "GRIME",
            "GRIND",
            "GRINE",
            "GRISE",
            "GRISK",
            "GROFT",
            "GROVE",
            "GROVS",
            "GRUBE",
            "GRUMS",
            "GRUND",
            "GRUSE",
            "GRYDE",
            "GRYNT",
            "GRÆDE",
            "GRÆDT",
            "GRÆSK",
            "GRØDE",
            "GRØFT",
            "GRØNT",
            "GRÅNE",
            "GRÅTS",
            "GUANO",
            "GUAVA",
            "GUBBE",
            "GUDST",
            "GUFFE",
            "GUFLE",
            "GUIDE",
            "GULNE",
            "GUMLE",
            "GUMME",
            "GUMMI",
            "GUMPE",
            "GUNST",
            "GUPPY",
            "GYDER",
            "GYDES",
            "GYDTE",
            "GYDTS",
            "GYLLE",
            "GYLPE",
            "GYLTE",
            "GYNGE",
            "GYSEN",
            "GYSER",
            "GYSES",
            "GYSTE",
            "GYTJE",
            "GYVEL",
            "GÆKKE",
            "GÆLDE",
            "GÆLDT",
            "GÆLER",
            "GÆLLE",
            "GÆNGE",
            "GÆNGS",
            "GÆRDE",
            "GÆSES",
            "GÆSTE",
            "GÆTTE",
            "GØDES",
            "GØGLE",
            "GØNGE",
            "GØREN",
            "GØRES",
            "GØSES",
            "GÅBEN",
            "GÅEDE",
            "GÅETS",
            "GÅLÆG",
            "GÅSEN",
            "GÅSES",
            "GÅTID",
            "GÅTUR",
            "HABIL",
            "HABIT",
            "HACKE",
            "HADER",
            "HADSK",
            "HAGLE",
            "HAIKU",
            "HAKKE",
            "HALET",
            "HALLO",
            "HALMA",
            "HALON",
            "HALSE",
            "HALTE",
            "HALTS",
            "HALVT",
            "HALVØ",
            "HAMLE",
            "HAMME",
            "HAMRE",
            "HANDY",
            "HANKE",
            "HAPSE",
            "HAREM",
            "HARKE",
            "HARME",
            "HARMS",
            "HARPE",
            "HARPY",
            "HARSK",
            "HARVE",
            "HASPE",
            "HASTE",
            "HAUSA",
            "HAVDE",
            "HAVES",
            "HAVIS",
            "HAVNE",
            "HAVRE",
            "HAVÅL",
            "HEADE",
            "HEALE",
            "HEAVY",
            "HEDDE",
            "HEDEN",
            "HEGLE",
            "HEGNE",
            "HEILE",
            "HEJRE",
            "HEJSA",
            "HEJSE",
            "HEKSE",
            "HELIX",
            "HELLE",
            "HELME",
            "HELOT",
            "HELSE",
            "HELST",
            "HELTE",
            "HELÅR",
            "HEMAN",
            "HENAD",
            "HENDE",
            "HENDØ",
            "HENGÅ",
            "HENLÅ",
            "HENNA",
            "HENNE",
            "HENRY",
            "HENSE",
            "HENSÅ",
            "HENTE",
            "HEPPE",
            "HERAF",
            "HERME",
            "HEROM",
            "HEROP",
            "HERPÅ",
            "HERRE",
            "HERSE",
            "HERTE",
            "HERTZ",
            "HERUD",
            "HERUT",
            "HETZE",
            "HEVEN",
            "HEVES",
            "HEVET",
            "HEVNE",
            "HEXAN",
            "HIDSE",
            "HIGEN",
            "HIHAT",
            "HIKKE",
            "HIKST",
            "HILDE",
            "HILLE",
            "HILSE",
            "HIMLE",
            "HINDE",
            "HINDI",
            "HINDU",
            "HINES",
            "HINKE",
            "HINTS",
            "HIRSE",
            "HISSE",
            "HITTE",
            "HIVEN",
            "HIVER",
            "HIVES",
            "HJALD",
            "HJALP",
            "HJELM",
            "HJORD",
            "HJORT",
            "HJULE",
            "HJÆLP",
            "HOBBY",
            "HOBEN",
            "HOFTE",
            "HOLDE",
            "HOLDT",
            "HOOKE",
            "HOPLA",
            "HOPPE",
            "HOPSA",
            "HORDE",
            "HORST",
            "HOSTE",
            "HOTEL",
            "HOUSE",
            "HOVED",
            "HOVEN",
            "HOVNE",
            "HOVSA",
            "HTTPS",
            "HUDRE",
            "HUGAF",
            "HUGGE",
            "HUGST",
            "HUHEJ",
            "HUJEN",
            "HULKE",
            "HULLE",
            "HULTE",
            "HULTS",
            "HUMAN",
            "HUMLE",
            "HUMME",
            "HUMOR",
            "HUMPE",
            "HUMUS",
            "HUMØR",
            "HUNDE",
            "HURRA",
            "HUSAR",
            "HUSKE",
            "HUSLY",
            "HUTLE",
            "HUTRE",
            "HVALP",
            "HVEDE",
            "HVENE",
            "HVEPS",
            "HVERS",
            "HVERT",
            "HVERV",
            "HVIDE",
            "HVIDS",
            "HVILE",
            "HVINE",
            "HVORI",
            "HVÆLV",
            "HVÆSE",
            "HYBEL",
            "HYBEN",
            "HYDRA",
            "HYGGE",
            "HYKLE",
            "HYLDE",
            "HYLEN",
            "HYLER",
            "HYLLE",
            "HYMEN",
            "HYMNE",
            "HYNDE",
            "HYPER",
            "HYPPE",
            "HYRDE",
            "HYSSE",
            "HYTTE",
            "HYÆNE",
            "HÆDER",
            "HÆDRE",
            "HÆFTE",
            "HÆGTE",
            "HÆKLE",
            "HÆLDE",
            "HÆLER",
            "HÆLVT",
            "HÆMME",
            "HÆNDE",
            "HÆNGE",
            "HÆNGT",
            "HÆRDE",
            "HÆRGE",
            "HÆTTE",
            "HÆVDE",
            "HÆVER",
            "HÆVET",
            "HÆVNE",
            "HØFDE",
            "HØJDE",
            "HØJNE",
            "HØJRE",
            "HØJST",
            "HØKER",
            "HØKRE",
            "HØLÆS",
            "HØNEN",
            "HØNER",
            "HØNES",
            "HØNSE",
            "HØNSS",
            "HØRER",
            "HØRIG",
            "HØRME",
            "HØRTE",
            "HØRTS",
            "HØSTE",
            "HØTYV",
            "HØVED",
            "HØVLE",
            "HØVLS",
            "HÅNDE",
            "HÅNDS",
            "HÅNLE",
            "HÅNLO",
            "HÅNSK",
            "HÅRDT",
            "HÅRET",
            "ICING", "ICTOG", "IDEAL", "IDEEL", "IDEEN", "IDÉEN", "IDEER", "IDÉER", "IDELS", "IDIOM", "IDIOT", "IDRÆT", "IDØMT", "IFALD", "IFJOR", "IFØRE",
            "IGANG", "IGLOO", "IHJEL", "IKKUN", "ILAGT", "ILAND", "ILBUD", "ILDER", "ILDES", "ILDHU", "ILDNE", "ILING", "ILSOM", "ILTER", "ILTOG", "ILTRE",
            "IMAGE", "IMAGO", "IMENS", "IMMER", "IMMUN", "INDAD", "INDBO", "INDEN", "INDER", "INDEX", "INDGÅ", "INDRE", "INDSE", "INDSY", "INDSØ", "INDSÅ",
            "INDVI", "INERT", "INFAM", "INGEN", "INPUT", "INTER", "INTET", "INTIM", "INTRO", "INUIT", "IONEN", "IONER", "IRONI", "IRRET", "IRSKE", "IRSKS",
            "IRØRE", "ISATS", "ISBAR", "ISBLÅ", "ISBOD", "ISBRÆ", "ISBÅD", "ISFOD", "ISFRI", "ISHAL", "ISHAV", "ISHUS", "ISING", "ISLAG", "ISLAM", "ISLOM",
            "ISLÆG", "ISLÆT", "ISNEN", "ISOLI", "ISSYL", "ISTAP", "ISTEM", "ISTER", "ISTID", "ISYET", "ITEMS", "IVRIG", "JAGEN", "JAGER", "JAGES", "JAGET",
            "JAGNE", "JAGTE", "JAKET", "JAKKE", "JAMBE", "JAMEN", "JAMME", "JAMRE", "JANTE", "JAORD", "JAPPE", "JASKE", "JAVEL", "JAZZE", "JEANS", "JENSS",
            "JENTE", "JERES", "JERKE", "JERNE", "JETON", "JIHAD", "JINGE", "JOBBE", "JODLE", "JOGES", "JOGGE", "JOINE", "JOINT", "JOKER", "JOKKE", "JOLLE",
            "JOLRE", "JONEN", "JONER", "JORDE", "JOULE", "JUBEL", "JUBLE", "JUICE", "JULET", "JUMBE", "JUMBO", "JUMPE", "JUNGE", "JUNKE", "JUNTA", "JUVEL",
            "JYSKE", "JYSKS", "JÆGER", "JÆRPE", "JÆTTE", "JÆVNE", "JØKEL", "KABEL", "KABLE", "KABYS", "KADET", "KADRE", "KAFFE", "KAGLE", "KAHYT", "KAJAK",
            "KAKAO", "KALAS", "KALDE", "KALIF", "KALKE", "KALLA", "KALOT", "KALVE", "KAMEL", "KAMES", "KAMÉS", "KAMIK", "KAMIN", "KAMME", "KANAL", "KANDE",
            "KANEL", "KANIN", "KANNA", "KANON", "KANTE", "KANUT", "KAPEL", "KAPER", "KAPOK", "KAPPE", "KAPRE", "KAPUT", "KARAT", "KARDE", "KARET", "KARGO",
            "KARMA", "KARPE", "KARRE", "KARRÉ", "KARRY", "KARSE", "KARSK", "KARST", "KARTE", "KARVE", "KASKO", "KASSE", "KASTE", "KASUS", "KATAR", "KAVAJ",
            "KEBAB", "KEDEL", "KEDER", "KEDES", "KEFIR", "KEGLE", "KEJSE", "KEJTE", "KELIM", "KENDE", "KENDT", "KERNE", "KERTE", "KERUB", "KETCH", "KETLE",
            "KETON", "KHMER", "KIGGE", "KIKKE", "KIKSE", "KILDE", "KILTE", "KIMEN", "KIMSE", "KININ", "KIOSK", "KIPER", "KIPPE", "KIRKE", "KISEL", "KISTE",
            "KITIN", "KITTE", "KIVES", "KJOLE", "KJOVE", "KLAGE", "KLANG", "KLAPS", "KLARE", "KLASE", "KLASK", "KLEJN", "KLEMT", "KLERK", "KLIKE", "KLIMA",
            "KLINE", "KLING", "KLINK", "KLINT", "KLIPS", "KLIRE", "KLOAK", "KLODE", "KLODS", "KLOEN", "KLOGE", "KLONE", "KLORE", "KLOSS", "KLOVN", "KLUMP",
            "KLUNS", "KLYDE", "KLYNE", "KLYNK", "KLÆBE", "KLÆDE", "KLØER", "KLØFT", "KLØGT", "KLØJS", "KLØVE", "KNAGE", "KNALD", "KNARK", "KNARR", "KNASE",
            "KNAST", "KNIBE", "KNIKS", "KNIPS", "KNIRK", "KNOBE", "KNOBS", "KNOLD", "KNUBS", "KNUDE", "KNUGE", "KNUSE", "KNYST", "KNÆGT", "KNÆLE", "KOALA",
            "KOBEN", "KOBLE", "KOBRA", "KODER", "KOENS", "KOFTE", "KOGER", "KOGEØ", "KOGGE", "KOGLE", "KOKET", "KOKKE", "KOKON", "KOKOS", "KOKSE", "KOLBE",
            "KOLDE", "KOLIK", "KOLLI", "KOLON", "KOLOS", "KOMET", "KOMIK", "KOMMA", "KOMME", "KOMNE", "KOMØG", "KONDI", "KONET", "KONGE", "KONTI", "KONTO",
            "KONUS", "KOPAR", "KOPEK", "KOPRA", "KORAL", "KORAN", "KORDE", "KORNE", "KORPS", "KORSE", "KORTE", "KORTS", "KOSAK", "KOSTE", "KOØJE", "KRADS",
            "KRAFT", "KRAGE", "KRANE", "KRANK", "KRANS", "KRAVE", "KRAVL", "KREBS", "KREDS", "KREMS", "KREOL", "KRIDT", "KRIGS", "KRIMI", "KRISE", "KROAT",
            "KROGE", "KRONE", "KROPS", "KRUDT", "KRUSE", "KRYBE", "KRYDS", "KRYPT", "KRÆFT", "KRÆGE", "KRÆSE", "KRÆVE", "KRØJE", "KRAAL", "KRÅLS", "KRÅSE",
            "KUBIK", "KUBUS", "KUGLE", "KUJON", "KUKKE", "KUKUR", "KULAK", "KULDE", "KULLE", "KULOS", "KULSO", "KULØR", "KUMME", "KUNDE", "KUNNE", "KUNST",
            "KUPES", "KUPÉS", "KUPLE", "KUPON", "KUPPE", "KURER", "KURIE", "KURRE", "KURVE", "KUSKE", "KUSSE", "KUTTE", "KVAJE", "KVALM", "KVALT", "KVANT",
            "KVARK", "KVART", "KVASE", "KVASI", "KVAST", "KVIDE", "KVILT", "KVIND", "KVINT", "KVIST", "KVITS", "KVOTE", "KVÆDE", "KVÆGE", "KVÆLD", "KVÆLE",
            "KVÆRK", "KVÆRN", "KYLLE", "KYMRE", "KYPER", "KYRAS", "KYRIE", "KYSER", "KYSES", "KYSET", "KYSSE", "KYSTE", "KYSTS", "KÆFTE", "KÆLEN", "KÆLKE",
            "KÆLNE", "KÆLVE", "KÆMME", "KÆMPE", "KÆPPE", "KÆRNE", "KÆRRE", "KÆRTE", "KÆVLE", "KØBER", "KØDBY", "KØDET", "KØERS", "KØLER", "KØLET",
            "KØLIG", "KØLLE", "KØLNE", "KØRER", "KØRNE", "KØTER", "KÅRDE", "LABAN", "LABBE", "LABEL", "LABER", "LABIL", "LABRE", "LADER", "LADES", "LADET",
            "LADTE", "LADTS", "LADYS", "LAGDE", "LAGEN", "LAGER", "LAGET", "LAGRE", "LAGTE", "LAGTS", "LAKAJ", "LAKKE", "LALAS", "LALLE", "LAMEL", "LAMES",
            "LAMÉS", "LAMME", "LAMPE", "LANDE", "LANDS", "LANGE", "LANGS", "LANGT", "LANSE", "LAPIS", "LAPPE", "LARGE", "LARGO", "LARME", "LARVE", "LASER",
            "LASET", "LASKE", "LASSO", "LASTE", "LASUR", "LATEX", "LATIN", "LATTE", "LAVET", "LEASE", "LEBEN", "LEDDE", "LEDEN", "LEDER", "LEDES", "LEDET",
            "LEDIG", "LEDNE", "LEENS", "LEERS", "LEFLE", "LEGAL", "LEGAT", "LEGER", "LEGIO", "LEJDE", "LEJER", "LEJRE", "LEMMA", "LEMON", "LEMPE", "LEMUR",
            "LENDE", "LENTO", "LERET", "LETAL", "LETTE", "LEVEN", "LEVER", "LEVIT", "LEVNE", "LEVRE", "LIDEN", "LIDER", "LIDES", "LIDET", "LIDSE", "LIDTE",
            "LIDTS", "LIERE", "LIFTE", "LIGES", "LIGGE", "LIGHT", "LIGNE", "LIKØR", "LILJE", "LILLA", "LILLE", "LIMBO", "LIMER", "LIMIT", "LIMON", "LINDE",
            "LINER", "LINGE", "LINJE", "LINKE", "LINKS", "LINSE", "LIPID", "LIRER", "LIRES", "LIRET", "LIRKE", "LISEN", "LISTE", "LITER", "LITRA", "LIVER",
            "LIVES", "LIVRE", "LIVRÉ", "LOADE", "LOBBE", "LOBBY", "LODDE", "LODES", "LODNE", "LODSE", "LODUR", "LOGGE", "LOGIK", "LOGIN", "LOGOS", "LOGRE",
            "LOKAL", "LOKKE", "LOKUM", "LOMME", "LOMVI", "LONGE", "LOOPE", "LOPPE", "LOREN", "LORNE", "LOSES", "LOSSE", "LOTTE", "LOTTO", "LOTUS", "LOVEN",
            "LOYAL", "LUBBE", "LUDEN", "LUDER", "LUFFE", "LUFTE", "LUGAR", "LUGTE", "LUKAF", "LUKKE", "LULLE", "LUMEN", "LUMRE", "LUMSK", "LUNCH", "LUNDE",
            "LUNGE", "LUNKE", "LUNTE", "LUPIN", "LUPPE", "LUPUS", "LUREN", "LURER", "LUSET", "LUSKE", "LUTRE", "LUXES", "LYBSK", "LYDER", "LYDES", "LYDIG",
            "LYDTE", "LYDTS", "LYGTE", "LYKKE", "LYMFE", "LYNER", "LYNET", "LYNNE", "LYRIK", "LYSEN", "LYSIN", "LYSKE", "LYSNE", "LYSTE", "LYSÅR", "LYTTE",
            "LYVER", "LYVES", "LÆDER", "LÆGGE", "LÆGTE", "LÆKAT", "LÆKKE", "LÆKRE", "LÆMME", "LÆMUR", "LÆNGE", "LÆNKE", "LÆNSE", "LÆNSS", "LÆRDE", "LÆRDS",
            "LÆRER", "LÆRKE", "LÆSER", "LÆSKE", "LÆSPE", "LÆSSE", "LØBEN", "LØBER", "LØBES", "LØBET", "LØBNE", "LØBSK", "LØDES", "LØDIG", "LØFTE", "LØJER",
            "LØJES", "LØJET", "LØJPE", "LØKKE", "LØNNE", "LØSEN", "LØSER", "LØSNE", "LØVET", "LÅDNE", "LÅNER", "MACHO", "MACHS", "MACON", "MADAM", "MADOS",
            "MADRO", "MAFIA", "MAGER", "MAGES", "MAGMA", "MAGRE", "MAGTE", "MAILE", "MAILS", "MAJOR",
            "MAKKE", "MAKRO", "MALAJ", "MALER", "MALKE", "MALLE", "MALTE", "MAMBA", "MAMBO", "MAMMA", "MANAT", "MANDE", "MANDS", "MANEN", "MANER",
            "MANÉR", "MANGE", "MANGO", "MANGT", "MANKE", "MANKO", "MANNA", "MANNE", "MANTA", "MANUS", "MAORI", "MAPPE", "MARCH", "MARIN", "MARSK",
            "MARTS", "MASAI", "MASEN", "MASER", "MASKE", "MASSE", "MATCH", "MATES", "MATÉS", "MAUVE", "MAVSE", "MEDER", "MEDGÅ", "MEDIE", "MEDIO",
            "MEGEN", "MEGET", "MEJER", "MEJSE", "MEKKA", "MELDE", "MELET", "MELIS", "MELON", "MENED", "MENER", "MENES", "MENGE", "MENIG", "MENTE",
            "MERES", "MERIT", "MERLE", "MESAN", "MESON", "MESSE", "MESTE", "MESTS", "METAL", "METAN", "METER", "METRA", "METRE", "METRO", "METYL",
            "MEZZO", "MIAVE", "MIDJE", "MIDLE", "MIDTE", "MIDTI", "MIKKE", "MIKRO", "MIKSE", "MILDT", "MILES", "MILJØ", "MILLE", "MILLI", "MILTE",
            "MILTS", "MIMER", "MIMIK", "MIMRE", "MINDE", "MINES", "MINKE", "MINUS", "MINUT", "MINØR", "MISSE", "MISTE", "MITRA", "MITTE", "MJAVE",
            "MOBBE", "MOBIL", "MODAL", "MODEL", "MODEM", "MODEN", "MODER", "MODGÅ", "MODIG", "MODIS", "MODNE", "MODSØ", "MODUL", "MODUS", "MOGUL",
            "MOIRE", "MOIRÉ", "MOKKA", "MOKKE", "MOLBO", "MOLER", "MOLOK", "MOLÆR", "MOMSE", "MONNE", "MONTO", "MOPPE", "MORAK", "MORAL", "MOREL",
            "MOREN", "MORSE", "MOSKE", "MOSKÉ", "MOSLE", "MOSTE", "MOTEL", "MOTET", "MOTIV", "MOTOR", "MOTTO", "MUDRE", "MUFFE", "MUFLE", "MUFTI",
            "MUGGE", "MUGNE", "MUKKE", "MULAT", "MULDE", "MULIG", "MULKT", "MULLE", "MULTE", "MULTI", "MUMIE", "MUMLE", "MUNDE", "MURBI", "MURER",
            "MURHA", "MURRE", "MUSIK", "MUZAK", "MYNDE", "MYNTE", "MYOSE", "MYRDE", "MYRRA", "MYRTE", "MYSLI", "MÆCEN", "MÆGLE", "MÆGTE", "MÆLDE",
            "MÆLKE", "MÆNDS", "MÆNGE", "MÆRKE", "MÆSKE", "MÆTTE", "MØBEL", "MØDES", "MØDIG", "MØDOM", "MØDRE", "MØFFE", "MØGSO", "MØLLE", "MØNBO",
            "MØNJE", "MØNNE", "MØNSK", "MØNTE", "MØRKE", "MØRKT", "MØRNE", "MØVER", "MÅBEN", "MÅLER", "MÅNED", "MÅSKE", "MÅTTE", "NADIR", "NAFTA",
            "NAGLE", "NAKKE", "NALLE", "NALRE", "NAPPA", "NAPPE", "NARKO", "NARRE", "NASAL", "NASSE", "NATIV", "NATTE", "NATUE", "NATUR", "NAVEL",
            "NAVER", "NAVLE", "NAVNE", "NEDAD", "NEDEN", "NEDGÅ", "NEDOM", "NEDRE", "NEGER", "NEGLE", "NEGRE", "NEMME", "NERIE", "NERTZ", "NERVE",
            "NESTE", "NETOP", "NETTE", "NETTO", "NEURO", "NEVEN", "NEVES", "NEVET", "NEVNE", "NEXUS", "NICES", "NICHE", "NIECE", "NIKKE", "NIPPE",
            "NIPSE", "NISSE", "NITAL", "NITID", "NITTE", "NIVER", "NIVES", "NIØJE", "NIÅRS", "NOBEL", "NOBLE", "NODER", "NOGEN", "NOGET", "NOGLE",
            "NOKKE", "NOMEN", "NONET", "NONNE", "NOPPE", "NOPRE", "NORNE", "NORSK", "NOSSE", "NOTAR", "NOTAT", "NUBRE", "NUDEL", "NULRE", "NULTE",
            "NUMRE", "NUMSE", "NUPPE", "NURSE", "NUSES", "NUSLE", "NUSSE", "NUTID", "NUTTE", "NUVEL", "NYDER", "NYDES", "NYDTE", "NYDTS", "NYEST",
            "NYHED", "NYKKE", "NYLIG", "NYLON", "NYMFE", "NYNNE", "NYORD", "NYRIG", "NYSEN", "NYSER", "NYSES", "NYSNE", "NYSSE", "NYSTE", "NYSYN",
            "NYTTE", "NYTÅR", "NÆBES", "NÆBET", "NÆGTE", "NÆLDE", "NÆNNE", "NÆPPE", "NÆRIG", "NÆRME", "NÆRPÅ", "NÆSTE", "NÆVNE", "NØDEN", "NØDES",
            "NØDIG", "NØDTS", "NØFLE", "NØGEN", "NØGLE", "NØGNE", "NØJER", "NØJES", "NØJET", "NØKKE", "NØLEN", "NØLER", "NØRKE", "NØRRE", "NØSES",
            "NÅDIG", "NÅDLE", "OBLAT", "OBLIK", "OCEAN", "ODDER", "ODDSS", "ODEUR", "ODIØS", "OFFER", "OFRES", "OFRET", "OKAPI", "OKAYS", "OKKER",
            "OKTAN", "OKTAV", "OKTET", "OLDEN", "OLIET", "OMBUD", "OMBUK", "OMEGA", "OMEGN", "OMEND", "OMGAV", "OMGIK", "OMGIV", "OMGÆS", "OMGØR",
            "OMGÅR", "OMGÅS", "OMHUG", "OMHYL", "OMKAP", "OMKOM", "OMLYD", "OMLÆG", "OMLØB", "OMSAT", "OMSÆT", "OMVEJ", "ONANI", "ONKEL", "ONYKS",
            "OPART", "OPBAK", "OPBUD", "OPBYD", "OPBØD", "OPDUK", "OPERA", "OPFAR", "OPFEJ", "OPFOR", "OPGAV", "OPGIK", "OPGIV", "OPGØR", "OPGÅR",
            "OPGÅS", "OPHAV", "OPHUG", "OPHØR", "OPIUM", "OPKOG", "OPKOM", "OPKØB", "OPLAD", "OPLAG", "OPLOD", "OPLUK", "OPLYS", "OPLÆG", "OPLØB",
            "OPPER", "OPPES", "OPPET", "OPRET", "OPREV", "OPRIV", "OPRUL", "OPRYK", "OPRØM", "OPRØR", "OPRÅB", "OPSAT", "OPSIG", "OPSLÅ", "OPSTÅ",
            "OPSYN", "OPSÆT", "OPTAG", "OPTIK", "OPTIL", "OPTOG", "OPTUR", "OPTÆL", "OPVÆK", "OPÆDE", "OPÆDT", "OPØVE", "ORDEN", "ORDNE", "ORDRE",
            "ORGAN", "ORGEL", "ORGIE", "ORGLE", "ORGON", "ORKAN", "ORKIS", "ORLOG", "ORLOV", "ORNAT", "OSMAN", "OTIET", "OTIUM", "OTTER", "OUNCE",
            "OVENI", "PACER", "PADDE", "PADLE", "PAFFE", "PAGAJ", "PAJEN", "PAJER", "PAKET", "PAKIS", "PAKKE",
            "PALET", "PALLE", "PALME", "PAMPA", "PANDA", "PANDE", "PANEL", "PANIK", "PANTE", "PAPIL",
            "PAPIR", "PAPPE", "PARAT", "PARES", "PARÉS", "PARIA", "PARKA", "PARRE", "PARSE", "PARTI",
            "PARTY", "PARYK", "PASES", "PASHA", "PASSÉ", "PASSE", "PASTA", "PASTE", "PATER", "PATES",
            "PATÉS", "PATIO", "PATOS", "PATTE", "PAUKE", "PAUSE", "PEBEN", "PEBER", "PEBES", "PEBET",
            "PEBNE", "PEBRE", "PEDAL", "PEDEL", "PEELE", "PEJLE", "PELSE", "PENCE", "PENGE", "PENIS",
            "PENNY", "PENSA", "PEPPE", "PERCH", "PERLE", "PERSE", "PESTO", "PETIT", "PETTE", "PIANO",
            "PIBER", "PIBES", "PIBET", "PIBLE", "PICOT", "PIENS", "PIERS", "PIETÁ", "PIFFE", "PIFTE",
            "PIGET", "PIKER", "PIKES", "PIKÉS", "PIKKE", "PILAR", "PILKE", "PILLE", "PILNE", "PILOT",
            "PIMPE", "PINDE", "PINJE", "PINKS", "PINOL", "PINSE", "PINTE", "PINTS", "PINUP", "PIPPE",
            "PIQUE", "PIQUÉ", "PIRAT", "PIRKE", "PIROG", "PIROL", "PIRRE", "PISKE", "PISSE", "PIVOT",
            "PIXEL", "PIZZA", "PJALT", "PJANK", "PJASK", "PJECE", "PJEVS", "PJÆVE", "PLADE", "PLADS",
            "PLAGE", "PLAID", "PLANE", "PLANO", "PLASK", "PLAST", "PLEBS", "PLEJE", "PLEJL", "PLIGT",
            "PLING", "PLINT", "PLIRE", "PLUMP", "PLÆNE", "PLØJE", "PLØRE", "POCHE", "PODIE", "POESI",
            "POINT", "POKAL", "POKER", "POLAK", "POLAR", "POLET", "POLIO", "POLKA", "POLSK", "POLYP",
            "POLÆR", "POPPE", "PORET", "PORNO", "PORRE", "PORSE", "PORTO", "PORØS", "POSET", "POSTE",
            "POSTS", "POSØR", "POTTE", "POWER", "PRAGT", "PRAJE", "PRALE", "PRATE", "PRENT", "PRIMA",
            "PRIME", "PRIMO", "PRINS", "PRINT", "PRIOR", "PRISE", "PROBE", "PROSA", "PROVO", "PROXY",
            "PRUNK", "PRUST", "PRYDE", "PRYGL", "PRÆGE", "PRÆKE", "PRÆST", "PRØVE", "PSYKE", "PUDEL",
            "PUDRE", "PUDSE", "PUFFE", "PUKKE", "PUKLE", "PULJE", "PULLE", "PULSE", "PUMPE", "PUNCH",
            "PUNGE", "PUNKE", "PUNKT", "PUPIL", "PUPPE", "PURES", "PURÉS", "PURIN", "PURRE", "PUSES",
            "PUSHE", "PUSLE", "PUSTE", "PUTTE", "PYGMÆ", "PYLON", "PYLRE", "PYNTE", "PYRIT", "PYRUS",
            "PYTTE", "PYTØJ", "PÅLER", "PÅSKY", "PÅTRO", "PÅTUR", "PÅVIR", "QUARK", "QUART", "QUEEN",
            "QUEER", "QUOTA", "QUOTE", "RABAT", "RABBI", "RABLE", "RACER", "RADAR", "RADIO", "RADON", "RADSÅ", "RAFLE", "RAFTE",
            "RAGER", "RAIDE", "RAJAH", "RAKET", "RAKKE", "RAKLE", "RAKTE", "RAKTS", "RALLE", "RALLY",
            "RAMEN", "RAMLE", "RAMME", "RAMPE", "RAMTE", "RAMTS", "RANCH", "RANDT", "RANKE", "RAPID",
            "RAPPE", "RAPSE", "RASEN", "RASLE", "RASPE", "RASTE", "RATIO", "RAVEN", "RAYON", "REBEL",
            "REBUS", "RECES", "REDDE", "REDEN", "REDER", "REDES", "REDET", "REDNE", "REDTE", "REDTS",
            "REGAL", "REGEL", "REGIE", "REGNE", "REJFE", "REJSE", "REKYL", "REMIS", "REMIX", "REMSE",
            "RENDE", "RENSE", "RENTE", "REPOS", "RESAT", "RETTE", "RETUR", "REVEN", "REVES", "REVET",
            "REVIR", "REVLE", "REVNE", "REVSE", "RIBBE", "RIDER", "RIDES", "RIDSE", "RIFFS", "RIGEL",
            "RIGGE", "RIGID", "RIGLE", "RILLE", "RIMPE", "RIMTE", "RINDE", "RINGE", "RINKE", "RIPPE",
            "RISLE", "RISTE", "RITEN", "RITER", "RITES", "RITTE", "RITUS", "RIVAL", "RIVEN", "RIVER",
            "RIVES", "ROBOT", "ROBÅD", "ROCKE", "RODEN", "RODEO", "RODER", "RODET", "ROKKE", "ROLFE",
            "ROLIG", "ROLLE", "ROMAN", "ROMBE", "ROMER", "ROMMY", "RONDO", "ROSAS", "ROSEN", "ROSES",
            "ROSÉS", "ROSET", "ROSIN", "ROTOR", "ROTTE", "ROTUR", "ROUGE", "ROYAL", "RUBBE", "RUBEL",
            "RUBIN", "RUCHE", "RUDEL", "RUDER", "RUFLE", "RUGBY", "RUHED", "RULAM", "RULLE", "RUMBA",
            "RUMLE", "RUMME", "RUMPE", "RUNDE", "RUNDT", "RUNGE", "RUPEE", "RUPPE", "RURAL", "RUSKE",
            "RUSTE", "RUTTE", "RYDDE", "RYGER", "RYGES", "RYGTE", "RYKKE", "RYNKE", "RYSTE", "RYTME",
            "RÆERS", "RÆKKE", "RÆLIG", "RÆNKE", "RÆSON", "RØDEL", "RØDME", "RØDNE", "RØFLE", "RØGEN",
            "RØGES", "RØGET", "RØGNE", "RØGTE", "RØMME", "RØMTE", "RØMTS", "RØNNE", "RØRIG", "RØRÆG",
            "RØSTI", "RØVER", "RØVET", "RÅBEN", "RÅBER", "RÅBUK", "RÅDIG", "RÅDNE", "RÅDYR", "RÅENS",
            "RÅHED", "RÅHUS", "RÅKID", "RÅLAM", "RÅNOK", "RÅTRÆ", "RÅULD", "SABEL", "SABLE", "SADEL",
            "SADLE", "SAFIR", "SAFTE", "SAGDE", "SAGTE", "SAGTS", "SAKKE", "SAKSE", "SALAT", "SALDI",
            "SALDO", "SALEP", "SALGS", "SALIG", "SALME", "SALOL", "SALON", "SALPE", "SALSA", "SALTE",
            "SALTO", "SALTS", "SALUT", "SALVE", "SALÆR", "SAMBA", "SAMBO", "SAMER", "SAMLE", "SAMME",
            "SAMSK", "SAMSØ", "SANDE", "SANKE", "SANKS", "SANKT", "SANSE", "SARTE", "SARTS", "SATAN",
            "SATIN", "SATME", "SATSE", "SATTE", "SATYR", "SAUCE", "SAUNA", "SAVLE", "SAVNE", "SCENE",
            "SCOOP", "SCORE", "SEDAN", "SEEDE", "SEGNE", "SEJLE", "SEJRE", "SEJSE", "SEKEL", "SEKST",
            "SELEN", "SELVE", "SEMIT", "SENAT", "SENDE", "SENET", "SENIL", "SEPIA", "SERAF", "SERAS",
            "SERGE", "SERIE", "SERUM", "SERVE", "SERVO", "SESAM", "SETES", "SEXET", "SFÆRE", "SHEIK",
            "SHIIT", "SHINE", "SHTML", "SIBEN", "SIDDE", "SIDEN", "SIDSE", "SIDST", "SIFON", "SIGEL",
            "SIGER", "SIGES", "SIGMA", "SIGNE", "SIGTE", "SIKKE", "SIKRE", "SILDE", "SILEN", "SILER",
            "SILES", "SILET", "SILKE", "SILUR", "SIMRE", "SIMSE", "SINDE", "SINES", "SINKE", "SINUS",
            "SIOUX", "SIPPE", "SIRTS", "SIRUP", "SISAL", "SITAR", "SITEN", "SITES", "SITET", "SITRE",
            "SJASK", "SJOVE", "SJUFT", "SJUSK", "SJÆLE", "SKABE", "SKADE", "SKAFT", "SKAGE", "SKAKT",
            "SKALA", "SKALK", "SKALP", "SKANK", "SKARE", "SKARN", "SKARP", "SKARV", "SKAVE", "SKEDE",
            "SKEEN", "SKEER", "SKEJE", "SKEJS", "SKELE", "SKEMA", "SKETE", "SKIBE", "SKIDE", "SKIDT",
            "SKIFT", "SKILT", "SKIMT", "SKIND", "SKINK", "SKIVE", "SKJUL", "SKOLE", "SKOSE", "SKOVE",
            "SKOVL", "SKRAB", "SKRAL", "SKRAM", "SKRAP", "SKRAT", "SKRED", "SKREG", "SKREV", "SKRID",
            "SKRIG", "SKRIN", "SKRIV", "SKROG", "SKROT", "SKRUB", "SKRUD", "SKRUE", "SKRUK", "SKRUT",
            "SKRYD", "SKRÆK", "SKRÆL", "SKRÆM", "SKRÆP", "SKRÆV", "SKRØD", "SKRÅL", "SKRÅS", "SKRÅT",
            "SKUDE", "SKUDT", "SKUEN", "SKULE", "SKUNK", "SKURE", "SKURK", "SKURV", "SKVAT", "SKVÆT",
            "SKYDE", "SKYET", "SKYLD", "SKYTS", "SKÆLM", "SKÆLV", "SKÆMT", "SKÆND", "SKÆNE", "SKÆNK",
            "SKÆRE", "SKÆRF", "SKÆRM", "SKÆRV", "SKÆVE", "SKØDE", "SKØGE", "SKØNT", "SKØRE", "SKØRT",
            "SKÅLE", "SKÅNE", "SKÅRE", "SLAGS", "SLANG", "SLANK", "SLANT", "SLASK", "SLAVE", "SLESK",
            "SLIBE", "SLICE", "SLIDE", "SLIDS", "SLIDT", "SLIME", "SLIPS", "SLISK", "SLUDE", "SLUGE",
            "SLUGT", "SLUMP", "SLURK", "SLUSE", "SLYNG", "SLÆBE", "SLÆDE", "SLÆGT", "SLÆNG", "SLØJD",
            "SLØJE", "SLØRE", "SLØSE", "SLØVE", "SLÅEN", "SLÅER", "SLÅET", "SMAGE", "SMAGS", "SMALL",
            "SMART", "SMASH", "SMASK", "SMEDE", "SMELT", "SMIDE", "SMIDT", "SMILE", "SMOVS", "SMUDS",
            "SMULD", "SMULE", "SMULT", "SMURT", "SMYGE", "SMÆDE", "SMÆLD", "SMØGE", "SMØLE", "SMØRE",
            "SMÅBY", "SMÅLE", "SMÅLO", "SNACK", "SNAGE", "SNAPS", "SNARE", "SNART", "SNASK", "SNAVS",
            "SNEEN", "SNEET", "SNEGL", "SNERT", "SNIGE", "SNILD", "SNIPE", "SNIVE", "SNOET", "SNOLD",
            "SNORE", "SNORK", "SNUDE", "SNUSE", "SNUSK", "SNYDE", "SNYDT", "SNÆRE", "SNÆRT", "SNØFT",
            "SNØRE", "SNØVL", "SNØVS", "SOBER", "SOBRE", "SODET", "SOENS", "SOIRE", "SOIRÉ", "SOLDE",
            "SOLGT", "SOLID", "SOLIS", "SOLOS", "SOLUR", "SOLÅR", "SOMME", "SOMRE", "SONAR", "SONDE",
            "SONET", "SONOR", "SOPPE", "SORTE", "SORTS", "SOUND", "SOVEN", "SOVER", "SOVES", "SOVET",
            "SOVNE", "SOVSE", "SPADE", "SPALT", "SPAMS", "SPAND", "SPANG", "SPANT", "SPARE", "SPARK",
            "SPEED", "SPEGE", "SPEJL", "SPELT", "SPERM", "SPIDS", "SPIES", "SPILD", "SPILE", "SPIND",
            "SPION", "SPIRE", "SPISE", "SPJÆT", "SPLAT", "SPLID", "SPLIT", "SPOLE", "SPORE", "SPORT",
            "SPOVE", "SPRAK", "SPRAY", "SPRIT", "SPROG", "SPRUT", "SPRÆK", "SPRÆL", "SPRÆT", "SPRØD",
            "SPULE", "SPUNS", "SPURT", "SPURV", "SPÆDE", "SPÆGE", "SPÆND", "SPÆNE", "SPØGE", "SPØJS",
            "SPØRG", "SQUAW", "SSELE", "STADE", "STADS", "STAGE", "STALD", "STAMP", "STAND", "STANG",
            "STANK", "START", "STASE", "STAVE", "STAVN", "STEDE", "STEDT", "STEGE", "STEJL", "STELE",
            "STEMT", "STENE", "STIFT", "STIGE", "STILE", "STILK", "STILL", "STIME", "STIND", "STING",
            "STINK", "STIVE", "STIVS", "STJAL", "STJÆL", "STOLA", "STOLE", "STOLT", "STORE", "STORK",
            "STORM", "STORS", "STORT", "STORY", "STOSE", "STOUT", "STOVT", "STRAF", "STRAM", "STRED",
            "STREG", "STRID", "STRIK", "STRIP", "STROP", "STRUD", "STRUT", "STRYG", "STRÆB", "STRÆK",
            "STRØG", "STRØM", "STUDS", "STUMP", "STUND", "STUNT", "STUTS", "STUVE", "STYKS", "STYLE",
            "STYNE", "STYRE", "STYRT", "STÆNK", "STÆRK", "STÆSE", "STÆVN", "STØBE", "STØBT", "STØDE",
            "STØDT", "STØJE", "STØVE", "STÅET", "SUDER", "SUGEN", "SUGER", "SUITE", "SUJET", "SUKAT",
            "SUKKE", "SUKRE", "SULFO", "SULKY", "SULTE", "SULÅN", "SUMAK", "SUMME", "SUNDE", "SUPER",
            "SUPPE", "SUPRE", "SURFE", "SURRE", "SUSEN", "SUSHI", "SUTTE", "SUTUR", "SVADA", "SVAGE",
            "SVAGT", "SVAJE", "SVALE", "SVAMP", "SVANE", "SVANG", "SVANS", "SVARE", "SVART", "SVEDE",
            "SVEDT", "SVEJF", "SVEJS", "SVEND", "SVIDE", "SVIER", "SVIGE", "SVIGT", "SVIME", "SVIND",
            "SVINE", "SVING", "SVIRE", "SVIRP", "SVOVL", "SVÆLG", "SVÆRD", "SVÆRG", "SVÆRM", "SVÆVE",
            "SVØBE", "SWING", "SYDEN", "SYDOM", "SYDPÅ", "SYGNE", "SYLTE", "SYNDE", "SYNDS", "SYNES",
            "SYNGE", "SYNKE", "SYNSK", "SYNÅL", "SYREN", "SYRER", "SYRET", "SYRNE", "SYSLE", "SYTØJ",
            "SYVER", "SYVTI", "SÆKKE", "SÆLGE", "SÆNKE", "SÆRBO", "SÆSON", "SÆTER", "SÆTTE", "SØBAD",
            "SØDME", "SØERS", "SØGEN", "SØGER", "SØGTE", "SØGTS", "SØJLE", "SØKOK", "SØKOS", "SØLET",
            "SØLIV", "SØLJE", "SØLLE", "SØMIL", "SØMME", "SØREN", "SØRET", "SØRGE", "SØRIG", "SØRME",
            "SØSAT", "SØSYG", "SØSÆT", "SØULK", "SØVEJ", "SØVNE", "SÅBED", "SÅDAN", "SÅGAR", "SÅPAS",
            "SÅSOM", "SÅSÆD", "SÅTID", "SÅVEL", "TABEL", "TABER", "TABTE", "TABTS", "TACKL", "TACOS",
            "TAGEN", "TAGER", "TAGES", "TAGET", "TAGGE", "TAGNE", "TAJGA", "TAKKE", "TAKLE", "TAKSI",
            "TAKST", "TALAR", "TALEN", "TALER",
            "TALJE", "TALON", "TALTE", "TALTS", "TAMIL", "TAMPE", "TANDE", "TANDS", "TANGA", "TANGE",
            "TANGO", "TANGS", "TANKE", "TANTE", "TAPET", "TAPIR", "TAPPE", "TAPRE", "TARIF", "TAROK",
            "TAROT", "TASKE", "TASSE", "TASTE", "TATAR", "TATER", "TAVLE", "TAVSE", "TAVST", "TAXIE",
            "TAZET", "TEAMS", "TEEDE", "TEENS", "TEERS", "TEGNE", "TEHUS", "TEINT", "TEJST", "TEKOP",
            "TEKST", "TELEX", "TELTE", "TEMPI", "TEMPO", "TENOR", "TEORI", "TERME", "TERMO", "TERNE",
            "TERPE", "TERRE", "TERTS", "TESKE", "TESTE", "THETA", "THUJA", "THYBO", "TIARA", "TICSS",
            "TIDEN", "TIEDE", "TIERE", "TIEST", "TIETS", "TIGER", "TIGGE", "TIGRE", "TIKKE", "TILDE",
            "TILGÅ", "TILSE", "TILSÅ", "TILTE", "TIMER", "TIMES", "TIMID", "TINDE", "TINGE", "TINTE",
            "TIPPE", "TIRRE", "TISKE", "TISSE", "TITAL", "TITAN", "TITEL", "TITTE", "TIØRE", "TIÅRS",
            "TJALD", "TJANS", "TJAVS", "TJEKS", "TJENE", "TJEPT", "TJÆRE", "TJØRN", "TOAST", "TOBAK",
            "TOBIS", "TODDY", "TOFTE", "TOGES", "TOLDE", "TOLKE", "TOMAT", "TOMLE", "TOMME", "TONAL",
            "TONER", "TONET", "TONIC", "TONSE", "TONST", "TOPAS", "TOPPE", "TOPTI", "TORSK", "TORSO",
            "TOSSE", "TOTAL", "TOTEM", "TOTNE", "TOTTE", "TOUCH", "TOUGH", "TOUPE", "TOUPÉ", "TOÅRS",
            "TRACE", "TRACÉ", "TRAGT", "TRAIN", "TRAKT", "TRAMP", "TRANE", "TRANG", "TRAVE", "TRAVL",
            "TRAWL", "TREER", "TREMA", "TREND", "TREST", "TREVL", "TRIAS", "TRICK", "TRIND", "TRINE",
            "TRIOL", "TRIST", "TRIVI", "TRODS", "TROFÆ", "TROKÆ", "TROLD", "TRONE", "TROPE", "TRUCK",
            "TRUET", "TRUMF", "TRUNK", "TRUST", "TRYGT", "TRYKT", "TRYNE", "TRÆDE", "TRÆET", "TRÆLS",
            "TRÆNE", "TRÆSK", "TRÆVL", "TRØJE", "TRØST", "TRÅDE", "TRÅDT", "TUDEN", "TUDSE", "TUGTE",
            "TUKAN", "TULLE", "TULRE", "TUMLE", "TUMOR", "TUMPE", "TUNER", "TUNGE", "TURBO", "TURDE",
            "TURNE", "TURNÉ", "TUSCH", "TUSKE", "TUSSE", "TUTOR", "TUTTE", "TUTTI", "TVANG", "TVDÆK",
            "TVEBO", "TVIND", "TVINE", "TVING", "TVIST", "TVIVL", "TVRUM", "TVTID", "TVÆRE", "TVÆRS",
            "TVÆRT", "TWEED", "TWILL", "TWIST", "TYDER", "TYFON", "TYFUS", "TYGGE", "TYKKE", "TYKNE",
            "TYLLE", "TYLVT", "TYNDE", "TYNDT", "TYNGE", "TYRAN", "TYSKE", "TYSKS", "TYSSE", "TYSTE",
            "TYSTS", "TYVER", "TYVTE", "TÆERS", "TÆKKE", "TÆLLE", "TÆMME", "TÆNDE", "TÆNKE", "TÆNKT",
            "TÆPPE", "TÆRET", "TÆRSK", "TÆRTE", "TÆSKE", "TÆSKS", "TÆTNE", "TÆTTE", "TÆVEN", "TØFFE",
            "TØFLE", "TØJLE", "TØJRE", "TØJTE", "TØMME", "TØMRE", "TØMTE", "TØMTS", "TØNDE", "TØRIS",
            "TØRKE", "TØRNE", "TØRRE", "TØRST", "TØSET", "TØSNE", "TØVEN", "TÅENS", "TÅGET", "TÅLED",
            "TÅRNE", "UANET", "UBLID", "UBLUS", "UDBAD", "UDBED", "UDBUD", "UDBYD", "UDBØD", "UDDØD",
            "UDDØR", "UDDØS", "UDELT", "UDFRA", "UDFRI", "UDGAV", "UDGIK", "UDGIV", "UDGYD", "UDGØD",
            "UDGØR", "UDGÅR", "UDGÅS", "UDHUG", "UDHUS", "UDKIG", "UDKIK", "UDKOG", "UDKOM", "UDLER",
            "UDLES", "UDLET", "UDLOS", "UDLYD", "UDLÆG", "UDLØB", "UDLÅN", "UDPAK", "UDPEB", "UDPIB",
            "UDREV", "UDRIV", "UDRØJ", "UDRÅB", "UDSAT", "UDSER", "UDSES", "UDSET", "UDSIG", "UDSPY",
            "UDSTÅ", "UDSYN", "UDSÆD", "UDSÆT", "UDSÅS", "UDTAG", "UDTOG", "UDTUR", "UDTØM", "UDVEJ",
            "UDØBT", "UDØRK", "UDØSE", "UDØVE", "UEFNE", "UEGAL", "UENIG", "UENSS", "UFIKS", "UFRED",
            "UFROM", "UFØDT", "UFØRE", "UGIFT", "UGLAD", "UGRÆS", "UHELD", "UHYRE", "UHØRT", "UJÆVN",
            "UKLAR", "UKLOG", "ULAND", "ULAVE", "ULDEN", "ULDNE", "ULIGE", "ULTRA", "ULYST", "ULÆRD",
            "ULÆST", "ULØST", "ULÅST", "UMAGE", "UMBRA", "UMILD", "UNDER", "UNDGÅ", "UNDRE", "UNDSE",
            "UNDSÅ", "UNDTE", "UNDTS", "UNGES", "UNGMØ", "UNGTS", "UNIKA", "UNION", "UNODE", "UNÅDE",
            "URBAN", "UREDE", "UREDT", "UREEL", "URHAV", "URREM", "URTID", "URUND", "URÆMI", "URØRT",
            "USAGT", "USAND", "USKET", "USKIK", "USKØN", "USLES", "USSEL", "USUND", "USUSS", "UTALT",
            "UTIDE", "UTING", "UTOPI", "UTROS", "UTRYG", "UTUGT", "UTYSK", "UVANE", "UVANT", "UVEJR",
            "UVORN", "UÆGTE", "UØVET", "VABEL", "VABLE", "VAGER", "VAKLE", "VAKRE", "VAKTE", "VAKTS",
            "VALEN", "VALGT", "VALID", "VALKE", "VALLE", "VALNE", "VALSE", "VALTE", "VALØR", "VAMLE",
            "VANDE", "VANDT", "VANGE", "VANKE", "VANRY", "VANTE", "VANTS", "VARAN", "VARDE", "VARES",
            "VARIG", "VARME", "VARPE", "VARTE", "VARYL", "VASAL", "VASKE", "VATER", "VEDEL", "VEDET",
            "VEDGÅ", "VEENS", "VEERS", "VEGEN", "VEGES", "VEGET", "VEGNE", "VEJER", "VEJLE", "VEJRE",
            "VELAN", "VELIN", "VEMOD", "VENDE", "VENDT", "VENNE", "VENTE", "VENØS", "VERFE", "VERPE",
            "VERVE", "VERÅB", "VETOE", "VHALS", "VIDDE", "VIDEN", "VIDEO", "VIDES", "VIDJE", "VIDNE",
            "VIDST", "VIFTE", "VIGEN", "VIGER", "VIGES", "VIGTE", "VIGØR", "VIKAR", "VIKKE", "VIKLE",
            "VIKSE", "VILDT", "VILJE", "VILLA", "VILLE", "VIMRE", "VIMSE", "VINCA", "VINDE", "VINGE",
            "VINKE", "VINYL", "VINØS", "VIOLA", "VIPPE", "VIRAK", "VIRAL", "VIRAS", "VIRIL", "VIRKE",
            "VIRRE", "VIRUS", "VISAS", "VISER", "VISÉR", "VISIR", "VISIT", "VISKE", "VISNE", "VISSE",
            "VISUM", "VITAL", "VIVAT", "VLIES", "VODKA", "VOGTE", "VOILA", "VOKAL", "VOKSE", "VOLDE",
            "VOLFE", "VOLTE", "VOLTS", "VOLUT", "VORDE", "VORES", "VORTE", "VOTAS", "VOTUM", "VOVET",
            "VOVSE", "VRAGE", "VRANG", "VREDE", "VRIDE", "VRIST", "VRÆLE", "VRØVL", "VRÅLE", "VUERS",
            "VUETS", "VUGGE", "VULST", "VUNDE", "VUPPE", "VUPTI", "VYERS", "VYETS", "VÆBNE", "VÆDDE",
            "VÆDRE", "VÆGER", "VÆGRE", "VÆGTE", "VÆGUR", "VÆKKE", "VÆKST", "VÆLDE", "VÆLGE", "VÆLIG",
            "VÆLTE", "VÆNGE", "VÆNNE", "VÆRDI", "VÆRDS", "VÆREN", "VÆRES", "VÆRET", "VÆRFT", "VÆRGE",
            "VÆRKE", "VÆRNE", "VÆRRE", "VÆRST", "VÆSEL", "VÆSEN", "VÆSKE", "VÆTTE", "VÆVER", "VÆVRE",
            "VØLVE", "VÅBEN", "VÅDTE", "VÅGEN", "VÅGNE", "VÅNDE", "VÅSET", "WAGON", "WATTS", "WENGE",
            "WENGÉ", "WHIST", "XAKSE", "XENON", "YACHT", "YAKSE", "YATZY", "YDMYG", "YDRES", "YNDER",
            "YNDIG", "YNGEL", "YNGLE", "YNGRE", "YNGST", "YPPER", "YPPES", "YPPET", "YPPIG", "YUCCA",
            "ZAMBO", "ZAPPE", "ZEBRA", "ZEFYR", "ZELOT", "ZENIT", "ZINKE", "ZIPPE", "ZLOTY", "ZOBEL",
            "ZOOER", "ZOOME", "ZWECK", "ÆDELS", "ÆDELT", "ÆDERI", "ÆDLES", "ÆDRUS", "ÆDTES", "ÆGGER",
            "ÆGGES", "ÆGGET", "ÆGIDE", "ÆGTES", "ÆKELS", "ÆKELT", "ÆKLES", "ÆLDRE", "ÆLDST", "ÆLTER",
            "ÆLTET", "ÆNDER", "ÆNDRE", "ÆRBAR", "ÆRGRE", "ÆRLIG", "ÆRØBO", "ÆRØSK", "ÆSTET", "ÆVRED",
            "ØBOER", "ØDSEL", "ØDSLE", "ØFFER", "ØFFES", "ØFFET", "ØJERS", "ØJETS", "ØJNES", "ØKSNE",
            "ØLBAS", "ØLBIL", "ØLBOD", "ØLEJR", "ØLGÆR", "ØLLET", "ØLVOM", "ØMHED", "ØNSKE", "ØRIGE",
            "ØRKEN", "ØRRED", "ØSKEN", "ØSTAT", "ØSTEN", "ØSTOM", "ØSTPÅ", "ØSTRE", "ØSTUD", "ØVRES",
            "ØVRIG", "ÅBENS", "ÅBENT", "ÅBNER", "ÅBNES", "ÅBRED", "ÅDSEL", "ÅERNE", "ÅMAND", "ÅMÆND",
            "ÅNDET", "ÅNDIG", "ÅRBOG", "ÅRING", "ÅRLES", "ÅRLIG", "ÅRSAG", "ÅSTED"};

    public String randomOrd() {
        Random random = new Random();
        int i = random.nextInt(0, words.length+1);
        return words[i];
    }
    public String[] wordleOrdbog(){
        return this.words;
    }
}